model_list:
  - model_name: gpt-5.1
    litellm_params:
      model: openai/gpt-5.1
      api_key: os.environ/OPENAI_API_KEY

      # Optional: timeout, num_retries, temperature, max_tokens, etc.

  - model_name: gpt-5.1-codex
    litellm_params:
      model: openai/gpt-5.1
      api_key: os.environ/OPENAI_API_KEY

      # Optional: timeout, num_retries, temperature, max_tokens, etc.

  - model_name: gpt-5.1-codex-mini
    litellm_params:
      model: openai/gpt-5.1-codex-mini

      api_key: os.environ/OPENAI_API_KEY
      # Optional: timeout, num_retries, temperature, max_tokens, etc.

  - model_name: gpt-5.1-chat-latest
    litellm_params:
      model: openai/gpt-5.1-chat-latest

      api_key: os.environ/OPENAI_API_KEY
      # Optional: timeout, num_retries, temperature, max_tokens, etc.